# **Home Electricity Bill Forecasting with Time Series**

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
import tensorflow as tf
import joblib

### **Data Load and Assesement**

In [2]:
# load data
df = pd.read_csv('Consume.csv')
df.head()

   ID      Month  Days     Cost
0   1       July    30   99.642
1   2     August    31   93.694
2   3  September    30   96.668
3   4    October    31  101.103
4   5   November    30  104.115

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      19 non-null     int64
 1   Month   19 non-null     object
 2   Days    19 non-null     int64
 3   Cost    19 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 740.0+ bytes

In [4]:
# Drop ID
df_copy = df.copy()
df = df.drop(columns=['ID'])
df.head()

       Month  Days     Cost
0       July    30   99.642
1     August    31   93.694
2  September    30   96.668
3    October    31  101.103
4   November    30  104.115

In [5]:
# Statistic Descriptive
df.describe()

            Days        Cost
count  19.000000   19.000000
mean   30.473684   98.823000
std     0.772328    2.973225
min    28.000000   93.694000
25%    30.000000   96.784000
50%    31.000000   99.100000
75%    31.000000  100.801500
max    31.000000  104.115000

### **Data Pre-Processing**

In [6]:
# Encoding
encoder = OneHotEncoder(sparse_output=False)
month_enco = encoder.fit_transform(df[['Month']])

# Scaler
scaler = MinMaxScaler()
cost_scaled = scaler.fit_transform(df[['Cost']])

In [7]:
joblib.dump(encoder, 'encoder_ohe.pkl')
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']

In [8]:
# Gabungkan fetaures (Month OHE + Days)
X = np.hstack((month_enco, df[['Days']].values))
y = cost_scaled

In [9]:
# Reshape X untuk LSTM : (samples, time_steps, features)
X = X.reshape((X.shape[0], 1, X.shape[1]))

In [10]:
X

array([[[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         30.]],

       [[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         30.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         30.]],

       [[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         28.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         30.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         30.]],

       [[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         30.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         30.]],

       [[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]]])

### **Modelling**

In [11]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X.shape[1], X.shape[2])),
    LSTM(64, activation='relu', return_sequences=False),
    Dense(32, activation='relu'),
    Dense(1) # Output prediksi biaya
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.fit(X, y, epochs=100, verbose=1)

# Simpan model
model.save('model_listrik.h5')

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 7s 7s/step - loss: 0.1325 - mae: 0.2999
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step - loss: 0.0805 - mae: 0.2324
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0730 - mae: 0.2194
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step - loss: 0.0855 - mae: 0.2378
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - loss: 0.0912 - mae: 0.2460
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step - loss: 0.0858 - mae: 0.2384
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 249ms/step - loss: 0.0763 - mae: 0.2227
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step - loss: 0.0692 - mae: 0.2125
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - loss: 0.0675 - mae: 0.2095
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - loss: 0.0702 - mae: 0.2140
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - loss: 0.0735 - mae: 0.2201
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - loss: 0.0741 - mae: 0.2217
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step - loss: 0.0716 - mae: 0.2168
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - loss: 0.0675 - mae: 0.2092
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - loss: 0.0641 - mae: 0.2025
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step - loss: 0.0626 - mae: 0.2000
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step - loss: 0.0631 - mae: 0.2007
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - loss: 0.0642 - mae: 0.2029
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 205ms/step - loss: 0.0646 - mae: 0.2032
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - loss: 0.0637 - mae: 0.2015
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - loss: 0.0617 - mae: 0.1980
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 0.0595 - mae: 0.1937
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 0.0581 - mae: 0.1908
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.0576 - mae: 0.1904
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 0.0578 - mae: 0.1898
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step - loss: 0.0579 - mae: 0.1896
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - loss: 0.0573 - mae: 0.1885
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 0.0561 - mae: 0.1861
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - loss: 0.0546 - mae: 0.1839
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.0535 - mae: 0.1819
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - loss: 0.0529 - mae: 0.1799
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step - loss: 0.0526 - mae: 0.1793
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - loss: 0.0523 - mae: 0.1783
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.0517 - mae: 0.1769
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - loss: 0.0508 - mae: 0.1751
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - loss: 0.0497 - mae: 0.1729
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - loss: 0.0488 - mae: 0.1713
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - loss: 0.0482 - mae: 0.1703
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - loss: 0.0477 - mae: 0.1691
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - loss: 0.0472 - mae: 0.1677
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.0465 - mae: 0.1661
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - loss: 0.0456 - mae: 0.1643
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - loss: 0.0447 - mae: 0.1623
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0439 - mae: 0.1602
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - loss: 0.0433 - mae: 0.1582
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - loss: 0.0427 - mae: 0.1562
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.0420 - mae: 0.1544
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - loss: 0.0412 - mae: 0.1527
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 0.0403 - mae: 0.1510
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - loss: 0.0395 - mae: 0.1494
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - loss: 0.0388 - mae: 0.1476
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - loss: 0.0381 - mae: 0.1457
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - loss: 0.0373 - mae: 0.1436
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.0364 - mae: 0.1413
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - loss: 0.0355 - mae: 0.1387
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 0.0346 - mae: 0.1361
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 0.0338 - mae: 0.1333
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 0.0329 - mae: 0.1305
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - loss: 0.0318 - mae: 0.1274
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0306 - mae: 0.1246
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - loss: 0.0293 - mae: 0.1222
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - loss: 0.0283 - mae: 0.1201
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.0273 - mae: 0.1176
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - loss: 0.0262 - mae: 0.1142
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 0.0251 - mae: 0.1103
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - loss: 0.0241 - mae: 0.1063
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - loss: 0.0230 - mae: 0.1030
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - loss: 0.0220 - mae: 0.1002
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - loss: 0.0210 - mae: 0.0976
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - loss: 0.0199 - mae: 0.0947
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 0.0189 - mae: 0.0912
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - loss: 0.0179 - mae: 0.0878
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 0.0169 - mae: 0.0848
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - loss: 0.0159 - mae: 0.0833
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 0.0149 - mae: 0.0822
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 0.0140 - mae: 0.0809
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.0131 - mae: 0.0796
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - loss: 0.0122 - mae: 0.0787
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 0.0114 - mae: 0.0776
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - loss: 0.0106 - mae: 0.0762
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.0099 - mae: 0.0744
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.0092 - mae: 0.0724
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 0.0087 - mae: 0.0708
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 0.0082 - mae: 0.0697
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 0.0078 - mae: 0.0694
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - loss: 0.0074 - mae: 0.0704
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step - loss: 0.0071 - mae: 0.0710
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - loss: 0.0069 - mae: 0.0710
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step - loss: 0.0067 - mae: 0.0707
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - loss: 0.0065 - mae: 0.0706
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 195ms/step - loss: 0.0064 - mae: 0.0700
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - loss: 0.0063 - mae: 0.0688
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - loss: 0.0061 - mae: 0.0677
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - loss: 0.0060 - mae: 0.0665
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.0058 - mae: 0.0647
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 0.0057 - mae: 0.0630
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 0.0055 - mae: 0.0623
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 0.0054 - mae: 0.0608
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.0052 - mae: 0.0589
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0051 - mae: 0.0580

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [12]:
model.save('model_listrik.keras')

### **Inference**

In [13]:
# --- DI FILE SEPARATE / SAAT INFERENCE ---
loaded_model = tf.keras.models.load_model('model_listrik.keras')

def prediksi_bulan_ini(nama_bulan, jumlah_hari):
    # 1. Encode bulan (Harus pakai encoder yang sama saat training)
    bulan_test = pd.DataFrame({'Month': [nama_bulan]})
    bulan_ohe = encoder.transform(bulan_test) # encoder dari proses training
    
    # 2. Gabungkan dengan Days
    input_data = np.hstack((bulan_ohe, [[jumlah_hari]]))
    
    # 3. Reshape untuk LSTM
    input_data = input_data.reshape((1, 1, input_data.shape[1]))
    
    # 4. Predict
    prediksi_scaled = loaded_model.predict(input_data)
    
    # 5. Balikkan nilai ke Rupiah (Inverse Scale)
    hasil_asli = scaler.inverse_transform(prediksi_scaled)
    return hasil_asli[0][0]

# Contoh Penggunaan:
print(f"Prediksi biaya: {prediksi_bulan_ini('January', 31)}")

d:\python\Lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 9 variables whereas the saved optimizer has 16 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 547ms/step
Prediksi biaya: 99.27704620361328