# **Home Electricity Bill Forecasting with Time Series**

In [23]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
import tensorflow as tf
import joblib

### **Data Load and Assesement**

In [2]:
# load data
df = pd.read_csv('Consume.csv')
df.head()

   ID      Month  Days     Cost
0   1       July    30   99.642
1   2     August    31   93.694
2   3  September    30   96.668
3   4    October    31  101.103
4   5   November    30  104.115

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      19 non-null     int64
 1   Month   19 non-null     object
 2   Days    19 non-null     int64
 3   Cost    19 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 740.0+ bytes

In [4]:
# Drop ID
df_copy = df.copy()
df = df.drop(columns=['ID'])
df.head()

       Month  Days     Cost
0       July    30   99.642
1     August    31   93.694
2  September    30   96.668
3    October    31  101.103
4   November    30  104.115

In [7]:
# Statistic Descriptive
df.describe()

            Days        Cost
count  19.000000   19.000000
mean   30.473684   98.823000
std     0.772328    2.973225
min    28.000000   93.694000
25%    30.000000   96.784000
50%    31.000000   99.100000
75%    31.000000  100.801500
max    31.000000  104.115000

### **Data Pre-Processing**

In [10]:
# Encoding
encoder = OneHotEncoder(sparse_output=False)
month_enco = encoder.fit_transform(df[['Month']])

# Scaler
scaler = MinMaxScaler()
cost_scaled = scaler.fit_transform(df[['Cost']])

In [24]:
joblib.dump(encoder, 'encoder_ohe.pkl')
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']

In [11]:
# Gabungkan fetaures (Month OHE + Days)
X = np.hstack((month_enco, df[['Days']].values))
y = cost_scaled

In [13]:
# Reshape X untuk LSTM : (samples, time_steps, features)
X = X.reshape((X.shape[0], 1, X.shape[1]))

In [14]:
X

array([[[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         30.]],

       [[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         30.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         30.]],

       [[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         28.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         30.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         30.]],

       [[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         30.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         30.]],

       [[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]],

       [[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         31.]]])

### **Modelling**

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X.shape[1], X.shape[2])),
    LSTM(64, activation='relu', return_sequences=False),
    Dense(32, activation='relu'),
    Dense(1) # Output prediksi biaya
])

model.compile(optimizer='adam', loss='mse')
model.fit(X, y, epochs=100, verbose=1)

# Simpan model
model.save('model_listrik.h5')

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - loss: 0.3286
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 0.2214
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 0.1437
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - loss: 0.0954
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - loss: 0.0735
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.0725
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 0.0845
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - loss: 0.1002
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 0.1122
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 0.1169
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - loss: 0.1141
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - loss: 0.1059
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - loss: 0.0950
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - loss: 0.0840
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 0.0749
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 0.0689
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - loss: 0.0664
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0669
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - loss: 0.0693
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - loss: 0.0725
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 0.0752
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 0.0767
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - loss: 0.0765
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - loss: 0.0748
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - loss: 0.0720
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 0.0688
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - loss: 0.0658
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 0.0634
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - loss: 0.0620
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - loss: 0.0615
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step - loss: 0.0618
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - loss: 0.0625
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - loss: 0.0631
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step - loss: 0.0634
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step - loss: 0.0632
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 242ms/step - loss: 0.0625
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 276ms/step - loss: 0.0614
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step - loss: 0.0601
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - loss: 0.0589
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step - loss: 0.0579
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step - loss: 0.0572
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - loss: 0.0569
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - loss: 0.0568
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - loss: 0.0568
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - loss: 0.0567
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.0564
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - loss: 0.0560
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - loss: 0.0554
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - loss: 0.0547
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - loss: 0.0540
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.0534
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.0529
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - loss: 0.0525
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - loss: 0.0522
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - loss: 0.0519
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - loss: 0.0516
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 0.0512
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - loss: 0.0507
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - loss: 0.0502
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 0.0497
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0491
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 0.0486
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.0482
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - loss: 0.0477
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - loss: 0.0473
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - loss: 0.0469
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - loss: 0.0465
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - loss: 0.0460
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - loss: 0.0455
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - loss: 0.0450
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 0.0444
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - loss: 0.0439
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - loss: 0.0434
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0429
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - loss: 0.0424
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - loss: 0.0419
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 0.0413
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0408
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 0.0402
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step - loss: 0.0396
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - loss: 0.0390
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - loss: 0.0384
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 0.0377
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - loss: 0.0371
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 0.0364
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 0.0358
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - loss: 0.0351
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 0.0343
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 0.0336
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - loss: 0.0329
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.0321
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 0.0313
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 0.0305
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - loss: 0.0296
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - loss: 0.0288
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - loss: 0.0279
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - loss: 0.0269
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 0.0260
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 0.0251
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 0.0241

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [19]:
model.save('model_listrik.keras')

### **Inference**

In [22]:
# --- DI FILE SEPARATE / SAAT INFERENCE ---
loaded_model = tf.keras.models.load_model('model_listrik.keras')

def prediksi_bulan_ini(nama_bulan, jumlah_hari):
    # 1. Encode bulan (Harus pakai encoder yang sama saat training)
    bulan_test = pd.DataFrame({'Month': [nama_bulan]})
    bulan_ohe = encoder.transform(bulan_test) # encoder dari proses training
    
    # 2. Gabungkan dengan Days
    input_data = np.hstack((bulan_ohe, [[jumlah_hari]]))
    
    # 3. Reshape untuk LSTM
    input_data = input_data.reshape((1, 1, input_data.shape[1]))
    
    # 4. Predict
    prediksi_scaled = loaded_model.predict(input_data)
    
    # 5. Balikkan nilai ke Rupiah (Inverse Scale)
    hasil_asli = scaler.inverse_transform(prediksi_scaled)
    return hasil_asli[0][0]

# Contoh Penggunaan:
print(f"Prediksi biaya: {prediksi_bulan_ini('January', 31)}")

d:\python\Lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 9 variables whereas the saved optimizer has 16 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 511ms/step
Prediksi biaya: 99.4359359741211